atoms_out: atoms

bin: scripts/

blast_cmd: blastn
blast_db_endings: [nhd, nhi, nhr, nin, nog, nsd, nsi, nsq]
blast_db_name: database
blast_db_type: nucl
blast_dir: /path/to/blast/bin 
blast_params: -task=blastn -evalue=0.00001 -min_raw_gapped_score 100 

circos_cmd: /path/to/circos/bin/
genome_data_dir: genomes
marker_min_length: 300
marker_dir: markers
mkblastdb_cmd: makeblastdb

psycho_delta: 200
psycho_cov: 3
psycho_out: hierarchies
psycho_ref: 0

pwsynteny_plot_params: -m 10 -c -s # add -s to plot sublevels
pwsynteny_indet_regions_window_size: 100000
pysuf: .py
python2_bin: ''

segmentation_cmd: /path/to/atomizer
sgmtn_alignment_ident: 70
sgmtn_alignment_maxgap: 13
sgmtn_alignment_minlen: 13

tmp_dir: ~/.tmp
